manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/BPanther-2000/SNAP-BONGOCAT
  projects:
    - name: SNAP-BONGOCAT
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
